- name: Deploy Calculator App
  hosts: local

  tasks:
    - name: Remove old containers
      docker_container:
        name: scientific-calculator
        state: absent
        force_kill: yes

    - name: Deploy Calculator App
      # run in background & interactive
      docker_container:
        name: scientific-calculator
        image: harsh4710/scientific-calculator
        state: started
        interactive: yes
        detach: yes